---
name: Test, Build, and Push Service Containers to AWS ECR
on:
  push:
    branches: [main, auth, user]
jobs:
  build-and-push-auth:
    name: Test, Build, and Push Auth Service to AWS ECR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/auth' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit Tests for Auth Service
        run: |
          cd ./auth-service
          go test ./test/... -v

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Auth Image to ECR
        id: build-auth-image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: yalecrush/auth
          IMAGE_TAG: latest
        run: |
          docker buildx build ./auth-service --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  build-and-push-user:
    name: Test, Build, and Push User Service to AWS ECR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/user' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit Tests for User Service
        run: |
          cd ./user-service
          go test ./test/... -v

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Auth Image to ECR
        id: build-user-image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: yalecrush/user
          IMAGE_TAG: latest
        run: |
          docker buildx build ./user-service --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
